// Copyright 2026 Zyvor AI Labs · https://zyvor.dev
// SPDX-License-Identifier: Apache-2.0

//! Ansible playbook generation

use super::ImageAnalysis;
use anyhow::Result;

/// Generate Ansible playbook
pub fn generate(analysis: &ImageAnalysis) -> Result<String> {
    let mut playbook = String::new();

    // Playbook header
    playbook.push_str("---\n");
    playbook.push_str("# Generated by guestkit blueprint\n");
    playbook.push_str(&format!(
        "# Source: {} {}\n",
        analysis.os_name, analysis.os_version
    ));
    playbook.push('\n');

    // Main playbook
    playbook.push_str("- name: Configure server\n");
    playbook.push_str("  hosts: all\n");
    playbook.push_str("  become: yes\n");
    playbook.push('\n');
    playbook.push_str("  vars:\n");
    playbook.push_str(&format!("    hostname: {}\n", analysis.hostname));
    playbook.push('\n');

    // Tasks
    playbook.push_str("  tasks:\n");

    // Set hostname
    playbook.push_str("    - name: Set hostname\n");
    playbook.push_str("      hostname:\n");
    playbook.push_str("        name: \"{{ hostname }}\"\n");
    playbook.push('\n');

    // Install packages
    if !analysis.packages.is_empty() {
        playbook.push_str("    - name: Install packages\n");

        if analysis.os_name.to_lowercase().contains("ubuntu")
            || analysis.os_name.to_lowercase().contains("debian")
        {
            playbook.push_str("      apt:\n");
            playbook.push_str("        name:\n");
            for pkg in analysis.packages.iter().take(10) {
                playbook.push_str(&format!("          - {}\n", pkg.name));
            }
            playbook.push_str("        state: present\n");
            playbook.push_str("        update_cache: yes\n");
        } else {
            // RHEL/CentOS/Fedora
            playbook.push_str("      yum:\n");
            playbook.push_str("        name:\n");
            for pkg in analysis.packages.iter().take(10) {
                playbook.push_str(&format!("          - {}\n", pkg.name));
            }
            playbook.push_str("        state: present\n");
        }
        playbook.push('\n');
    }

    // Configure services
    for service in &analysis.services {
        playbook.push_str(&format!("    - name: Configure {} service\n", service.name));
        playbook.push_str("      systemd:\n");
        playbook.push_str(&format!("        name: {}\n", service.name));
        playbook.push_str(&format!(
            "        enabled: {}\n",
            if service.enabled { "yes" } else { "no" }
        ));
        playbook.push_str(&format!("        state: {}\n", service.state));
        playbook.push('\n');
    }

    // Configure firewall if ports detected
    if !analysis.ports.is_empty() {
        playbook.push_str("    - name: Configure firewall\n");
        playbook.push_str("      firewalld:\n");
        playbook.push_str("        port: \"{{ item }}\"\n");
        playbook.push_str("        permanent: yes\n");
        playbook.push_str("        state: enabled\n");
        playbook.push_str("      loop:\n");
        for port in &analysis.ports {
            playbook.push_str(&format!("        - {}/{}\n", port.number, port.protocol));
        }
        playbook.push_str("      when: ansible_os_family == \"RedHat\"\n");
        playbook.push('\n');
    }

    // Create data directories
    for volume in &analysis.volumes {
        playbook.push_str(&format!(
            "    - name: Create data directory {}\n",
            volume.path
        ));
        playbook.push_str("      file:\n");
        playbook.push_str(&format!("        path: {}\n", volume.path));
        playbook.push_str("        state: directory\n");
        playbook.push_str("        mode: '0755'\n");
        playbook.push('\n');
    }

    // Handlers
    playbook.push_str("  handlers:\n");
    for service in &analysis.services {
        playbook.push_str(&format!("    - name: restart {}\n", service.name));
        playbook.push_str("      systemd:\n");
        playbook.push_str(&format!("        name: {}\n", service.name));
        playbook.push_str("        state: restarted\n");
        playbook.push('\n');
    }

    Ok(playbook)
}
