// Copyright 2026 Zyvor AI Labs · https://zyvor.dev
// SPDX-License-Identifier: Apache-2.0

//! Docker Compose file generation

use super::ImageAnalysis;
use anyhow::Result;

/// Generate Docker Compose file
pub fn generate(analysis: &ImageAnalysis) -> Result<String> {
    let mut compose = String::new();

    let service_name = sanitize_name(&analysis.hostname);

    // Compose file header
    compose.push_str("# Generated by guestkit blueprint\n");
    compose.push_str("version: '3.8'\n\n");

    // Services
    compose.push_str("services:\n");
    compose.push_str(&format!("  {}:\n", service_name));
    compose.push_str("    image: your-registry/image:latest  # Replace with your image\n");
    compose.push_str(&format!("    container_name: {}\n", service_name));
    compose.push_str(&format!("    hostname: {}\n", analysis.hostname));

    // Ports
    if !analysis.ports.is_empty() {
        compose.push_str("    ports:\n");
        for port in &analysis.ports {
            if port.number != 22 {
                // Skip SSH
                compose.push_str(&format!("      - \"{}:{}\"\n", port.number, port.number));
            }
        }
    }

    // Volumes
    if !analysis.volumes.is_empty() {
        compose.push_str("    volumes:\n");
        for (idx, volume) in analysis.volumes.iter().enumerate() {
            compose.push_str(&format!("      - {}_data:{}:rw\n", idx, volume.path));
        }
    }

    // Environment
    compose.push_str("    environment:\n");
    compose.push_str(&format!("      - HOSTNAME={}\n", analysis.hostname));
    compose.push_str(&format!("      - OS_NAME={}\n", analysis.os_name));
    compose.push_str(&format!("      - OS_VERSION={}\n", analysis.os_version));

    // Resource limits
    compose.push_str("    deploy:\n");
    compose.push_str("      resources:\n");
    compose.push_str("        limits:\n");
    compose.push_str("          cpus: '1.0'\n");
    compose.push_str("          memory: 1G\n");
    compose.push_str("        reservations:\n");
    compose.push_str("          cpus: '0.5'\n");
    compose.push_str("          memory: 512M\n");

    // Restart policy
    compose.push_str("    restart: unless-stopped\n");

    // Networks
    compose.push_str("    networks:\n");
    compose.push_str("      - app_network\n");

    // Health check (if web service detected)
    let has_http = analysis
        .ports
        .iter()
        .any(|p| p.number == 80 || p.number == 443);
    if has_http {
        compose.push_str("    healthcheck:\n");
        compose.push_str("      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:80\"]\n");
        compose.push_str("      interval: 30s\n");
        compose.push_str("      timeout: 10s\n");
        compose.push_str("      retries: 3\n");
        compose.push_str("      start_period: 40s\n");
    }

    // Dependent services (if databases detected)
    let mut dependent_services = Vec::new();

    for service in &analysis.services {
        if service.name.contains("mysql") || service.name.contains("mariadb") {
            dependent_services.push("mysql");
        } else if service.name.contains("postgresql") {
            dependent_services.push("postgresql");
        } else if service.name.contains("redis") {
            dependent_services.push("redis");
        }
    }

    // Add database services
    for db_service in &dependent_services {
        compose.push('\n');
        compose.push_str(&format!("  {}:\n", db_service));

        match *db_service {
            "mysql" => {
                compose.push_str("    image: mysql:8.0\n");
                compose.push_str("    environment:\n");
                compose.push_str("      - MYSQL_ROOT_PASSWORD=changeme\n");
                compose.push_str("      - MYSQL_DATABASE=app\n");
                compose.push_str("    volumes:\n");
                compose.push_str("      - mysql_data:/var/lib/mysql\n");
                compose.push_str("    ports:\n");
                compose.push_str("      - \"3306:3306\"\n");
            }
            "postgresql" => {
                compose.push_str("    image: postgres:15\n");
                compose.push_str("    environment:\n");
                compose.push_str("      - POSTGRES_PASSWORD=changeme\n");
                compose.push_str("      - POSTGRES_DB=app\n");
                compose.push_str("    volumes:\n");
                compose.push_str("      - postgres_data:/var/lib/postgresql/data\n");
                compose.push_str("    ports:\n");
                compose.push_str("      - \"5432:5432\"\n");
            }
            "redis" => {
                compose.push_str("    image: redis:7\n");
                compose.push_str("    volumes:\n");
                compose.push_str("      - redis_data:/data\n");
                compose.push_str("    ports:\n");
                compose.push_str("      - \"6379:6379\"\n");
            }
            _ => {}
        }

        compose.push_str("    networks:\n");
        compose.push_str("      - app_network\n");
        compose.push_str("    restart: unless-stopped\n");
    }

    // Volumes section
    compose.push_str("\nvolumes:\n");
    for (idx, _volume) in analysis.volumes.iter().enumerate() {
        compose.push_str(&format!("  {}_data:\n", idx));
    }
    for db_service in &dependent_services {
        compose.push_str(&format!("  {}_data:\n", db_service));
    }

    // Networks section
    compose.push_str("\nnetworks:\n");
    compose.push_str("  app_network:\n");
    compose.push_str("    driver: bridge\n");

    Ok(compose)
}

fn sanitize_name(name: &str) -> String {
    name.to_lowercase()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}
