// Copyright 2026 Zyvor AI Labs · https://zyvor.dev
// SPDX-License-Identifier: Apache-2.0

//! Plan export to various formats (bash, ansible, terraform)

use super::types::*;
use anyhow::Result;
use std::fmt::Write as FmtWrite;

/// Escape a string for safe interpolation into a shell script.
/// Wraps the value in single quotes with proper inner escaping.
fn shell_escape(s: &str) -> String {
    // Replace each single quote with: end quote, escaped quote, start quote
    let escaped = s.replace('\'', "'\\''");
    format!("'{}'", escaped)
}

/// Escape a string for use inside a sed 's/pattern/replacement/' expression.
/// Escapes sed special characters WITHOUT wrapping in quotes.
fn sed_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('/', "\\/")
        .replace('&', "\\&")
        .replace('\n', "\\n")
}

/// Exports fix plans to different formats
pub struct PlanExporter;

impl PlanExporter {
    /// Export plan as bash script
    pub fn to_bash(plan: &FixPlan) -> Result<String> {
        let mut script = String::new();

        writeln!(script, "#!/bin/bash")?;
        writeln!(
            script,
            "# Generated by GuestKit v{}",
            env!("CARGO_PKG_VERSION")
        )?;
        writeln!(script, "# Profile: {}", plan.profile)?;
        writeln!(script, "# VM: {}", plan.vm)?;
        writeln!(script, "# Generated: {}", plan.generated)?;
        writeln!(script)?;
        writeln!(script, "set -e")?;
        writeln!(script)?;
        writeln!(script, "echo \"Applying {} fixes...\"", plan.profile)?;
        writeln!(script)?;

        // Backup section
        writeln!(script, "# Create backup")?;
        writeln!(script, "BACKUP_DIR=\"/backup/$(date +%Y%m%d-%H%M%S)\"")?;
        writeln!(script, "mkdir -p \"$BACKUP_DIR\"")?;
        writeln!(script)?;

        // Generate operations
        for op in &plan.operations {
            Self::operation_to_bash(&mut script, op)?;
        }

        // Post-apply actions
        if !plan.post_apply.is_empty() {
            writeln!(script, "# Post-apply actions")?;
            for action in &plan.post_apply {
                Self::post_action_to_bash(&mut script, action)?;
            }
        }

        writeln!(script)?;
        writeln!(script, "echo \"✓ All fixes applied successfully\"")?;

        Ok(script)
    }

    /// Convert operation to bash commands
    fn operation_to_bash(script: &mut String, op: &Operation) -> Result<()> {
        writeln!(script, "# {}: {}", op.id, op.description)?;

        match &op.op_type {
            OperationType::FileEdit(fe) => {
                writeln!(script, "cp {} \"$BACKUP_DIR/\"", shell_escape(&fe.file))?;
                for change in &fe.changes {
                    writeln!(
                        script,
                        "sed -i 's/{}/{}/g' {}",
                        sed_escape(&change.before),
                        sed_escape(&change.after),
                        shell_escape(&fe.file)
                    )?;
                }
            }
            OperationType::FileWrite(fw) => {
                let parent = std::path::Path::new(&fw.path)
                    .parent()
                    .and_then(|p| p.to_str())
                    .unwrap_or("/");
                if parent != "/" && !parent.is_empty() {
                    writeln!(script, "mkdir -p {}", shell_escape(parent))?;
                }
                writeln!(
                    script,
                    "cat > {} << 'GUESTKIT_EOF'\n{}\nGUESTKIT_EOF",
                    shell_escape(&fw.path),
                    fw.content.trim_end_matches('\n')
                )?;
                if let Some(mode) = &fw.mode {
                    writeln!(
                        script,
                        "chmod {} {}",
                        shell_escape(mode),
                        shell_escape(&fw.path)
                    )?;
                }
            }
            OperationType::Symlink(sl) => {
                writeln!(
                    script,
                    "ln -sfn {} {}",
                    shell_escape(&sl.target),
                    shell_escape(&sl.link_path)
                )?;
            }
            OperationType::FileDelete(fd) => {
                if fd.missing_ok {
                    writeln!(script, "rm -f {}", shell_escape(&fd.path))?;
                } else {
                    writeln!(script, "rm {}", shell_escape(&fd.path))?;
                }
            }
            OperationType::PackageInstall(pi) => {
                let escaped_pkgs: Vec<String> =
                    pi.packages.iter().map(|p| shell_escape(p)).collect();
                writeln!(script, "dnf install -y {}", escaped_pkgs.join(" "))?;
            }
            OperationType::ServiceOperation(so) => {
                if let Some(state) = &so.state {
                    if state == "enabled" {
                        writeln!(script, "systemctl enable {}", shell_escape(&so.service))?;
                    }
                }
                if so.start {
                    writeln!(script, "systemctl start {}", shell_escape(&so.service))?;
                }
                if so.restart {
                    writeln!(script, "systemctl restart {}", shell_escape(&so.service))?;
                }
            }
            OperationType::SelinuxMode(sm) => {
                writeln!(
                    script,
                    "sed -i 's/SELINUX={}/SELINUX={}/g' {}",
                    sed_escape(&sm.current),
                    sed_escape(&sm.target),
                    shell_escape(&sm.file)
                )?;
            }
            OperationType::CommandExec(ce) => {
                // WARNING: CommandExec writes commands directly to the script.
                // Ensure ce.command comes from a trusted/validated source.
                writeln!(
                    script,
                    "# [CommandExec] Review the following command before running:"
                )?;
                writeln!(script, "{}", ce.command)?;
            }
            OperationType::FileCopy(fc) => {
                writeln!(
                    script,
                    "cp {} {}",
                    shell_escape(&fc.source),
                    shell_escape(&fc.destination)
                )?;
            }
            OperationType::DirectoryCreate(dc) => {
                if let Some(mode) = &dc.mode {
                    writeln!(
                        script,
                        "mkdir -p -m {} {}",
                        shell_escape(mode),
                        shell_escape(&dc.path)
                    )?;
                } else {
                    writeln!(script, "mkdir -p {}", shell_escape(&dc.path))?;
                }
            }
            OperationType::FilePermissions(fp) => {
                writeln!(
                    script,
                    "chmod {} {}",
                    shell_escape(&fp.mode),
                    shell_escape(&fp.path)
                )?;
                if let Some(owner) = &fp.owner {
                    writeln!(
                        script,
                        "chown {} {}",
                        shell_escape(owner),
                        shell_escape(&fp.path)
                    )?;
                }
            }
            OperationType::DriverInject(di) => {
                writeln!(
                    script,
                    "pnputil /add-driver {} /install  # driver: {}",
                    shell_escape(&di.inf_path),
                    shell_escape(&di.driver_name)
                )?;
            }
            OperationType::RegistryEdit(re) => {
                let new_data_str = re.new_data.to_string();
                writeln!(
                    script,
                    "echo \"Registry edit: {} \\\\ {} = {} (type: {})\"",
                    shell_escape(&re.key),
                    shell_escape(&re.value),
                    shell_escape(&new_data_str),
                    shell_escape(&re.data_type)
                )?;
                writeln!(
                    script,
                    "echo \"WARNING: Registry edits require Windows tools (reg.exe or regedit)\""
                )?;
            }
        }

        if let Some(validation) = &op.validation {
            // Intentionally not escaped: validation.command is a trusted shell command
            writeln!(
                script,
                "{} || {{ echo \"Validation failed for {}\"; exit 1; }}",
                validation.command,
                shell_escape(&op.id)
            )?;
        }

        writeln!(script)?;
        Ok(())
    }

    /// Convert post-apply action to bash
    fn post_action_to_bash(script: &mut String, action: &PostApplyAction) -> Result<()> {
        match action {
            PostApplyAction::ServiceRestart { services } => {
                for service in services {
                    writeln!(script, "systemctl restart {}", shell_escape(service))?;
                }
            }
            PostApplyAction::Validation { command, .. } => {
                // Intentionally not escaped: validation command is a trusted shell command
                writeln!(script, "{}", command)?;
            }
            PostApplyAction::Message { message } => {
                writeln!(script, "echo {}", shell_escape(message))?;
            }
            PostApplyAction::RebootRequired { reason } => {
                writeln!(
                    script,
                    "echo {}",
                    shell_escape(&format!("Reboot required: {}", reason))
                )?;
            }
        }
        Ok(())
    }

    /// Export plan as Ansible playbook
    pub fn to_ansible(plan: &FixPlan) -> Result<String> {
        let mut playbook = String::new();

        writeln!(playbook, "---")?;
        writeln!(playbook, "- name: GuestKit {} Fixes", plan.profile)?;
        writeln!(playbook, "  hosts: vm")?;
        writeln!(playbook, "  become: yes")?;
        writeln!(playbook, "  tasks:")?;

        if plan.metadata.tags.iter().any(|t| t == "inject-agent") {
            writeln!(playbook, "    - name: Install GuestKit agent binary")?;
            writeln!(playbook, "      copy:")?;
            writeln!(playbook, "        src: guestkit")?;
            writeln!(playbook, "        dest: /usr/local/bin/guestkit")?;
            writeln!(playbook, "        mode: '0755'")?;
            writeln!(playbook, "    - name: Install guestkit-agent systemd unit")?;
            writeln!(playbook, "      copy:")?;
            writeln!(playbook, "        src: guestkit-agent.service")?;
            writeln!(
                playbook,
                "        dest: /etc/systemd/system/guestkit-agent.service"
            )?;
            writeln!(playbook, "    - name: Enable guestkit-agent")?;
            writeln!(playbook, "      systemd:")?;
            writeln!(playbook, "        name: guestkit-agent")?;
            writeln!(playbook, "        enabled: yes")?;
            writeln!(playbook, "        daemon_reload: yes")?;
        }

        for op in &plan.operations {
            Self::operation_to_ansible(&mut playbook, op)?;
        }

        Ok(playbook)
    }

    /// Convert operation to Ansible task
    fn operation_to_ansible(playbook: &mut String, op: &Operation) -> Result<()> {
        writeln!(playbook, "    - name: {}", op.description)?;

        match &op.op_type {
            OperationType::FileEdit(fe) => {
                if let Some(change) = fe.changes.first() {
                    writeln!(playbook, "      lineinfile:")?;
                    writeln!(playbook, "        path: {}", fe.file)?;
                    writeln!(playbook, "        regexp: '^{}$'", change.before)?;
                    writeln!(playbook, "        line: '{}'", change.after)?;
                    writeln!(playbook, "        backup: yes")?;
                }
            }
            OperationType::FileWrite(fw) => {
                writeln!(playbook, "      copy:")?;
                writeln!(playbook, "        dest: {}", fw.path)?;
                writeln!(playbook, "        content: |")?;
                for line in fw.content.lines() {
                    writeln!(playbook, "          {}", line)?;
                }
                if let Some(mode) = &fw.mode {
                    writeln!(playbook, "        mode: '{}'", mode)?;
                }
            }
            OperationType::Symlink(sl) => {
                writeln!(playbook, "      file:")?;
                writeln!(playbook, "        src: {}", sl.target)?;
                writeln!(playbook, "        dest: {}", sl.link_path)?;
                writeln!(playbook, "        state: link")?;
                writeln!(playbook, "        force: yes")?;
            }
            OperationType::FileDelete(fd) => {
                writeln!(playbook, "      file:")?;
                writeln!(playbook, "        path: {}", fd.path)?;
                writeln!(playbook, "        state: absent")?;
            }
            OperationType::PackageInstall(pi) => {
                writeln!(playbook, "      package:")?;
                writeln!(playbook, "        name:")?;
                for pkg in &pi.packages {
                    writeln!(playbook, "          - {}", pkg)?;
                }
                writeln!(playbook, "        state: present")?;
            }
            OperationType::ServiceOperation(so) => {
                writeln!(playbook, "      service:")?;
                writeln!(playbook, "        name: {}", so.service)?;
                if let Some(state) = &so.state {
                    writeln!(playbook, "        enabled: {}", state == "enabled")?;
                }
                if so.start {
                    writeln!(playbook, "        state: started")?;
                }
            }
            OperationType::SelinuxMode(sm) => {
                writeln!(playbook, "      lineinfile:")?;
                writeln!(playbook, "        path: {}", sm.file)?;
                writeln!(playbook, "        regexp: '^SELINUX={}'", sm.current)?;
                writeln!(playbook, "        line: 'SELINUX={}'", sm.target)?;
                writeln!(playbook, "        backup: yes")?;
            }
            OperationType::CommandExec(ce) => {
                writeln!(playbook, "      command: {}", ce.command)?;
            }
            OperationType::FileCopy(fc) => {
                writeln!(playbook, "      copy:")?;
                writeln!(playbook, "        src: {}", fc.source)?;
                writeln!(playbook, "        dest: {}", fc.destination)?;
                writeln!(playbook, "        remote_src: yes")?;
                if fc.backup {
                    writeln!(playbook, "        backup: yes")?;
                }
            }
            OperationType::DirectoryCreate(dc) => {
                writeln!(playbook, "      file:")?;
                writeln!(playbook, "        path: {}", dc.path)?;
                writeln!(playbook, "        state: directory")?;
                if let Some(mode) = &dc.mode {
                    writeln!(playbook, "        mode: '{}'", mode)?;
                }
            }
            OperationType::FilePermissions(fp) => {
                writeln!(playbook, "      file:")?;
                writeln!(playbook, "        path: {}", fp.path)?;
                writeln!(playbook, "        mode: '{}'", fp.mode)?;
                if let Some(owner) = &fp.owner {
                    writeln!(playbook, "        owner: {}", owner)?;
                }
                if let Some(group) = &fp.group {
                    writeln!(playbook, "        group: {}", group)?;
                }
            }
            OperationType::RegistryEdit(re) => {
                writeln!(playbook, "      win_regedit:")?;
                writeln!(playbook, "        path: {}", re.key)?;
                writeln!(playbook, "        name: {}", re.value)?;
                writeln!(playbook, "        data: {}", re.new_data)?;
                writeln!(playbook, "        type: {}", re.data_type)?;
            }
            OperationType::DriverInject(di) => {
                writeln!(
                    playbook,
                    "      win_command: pnputil /add-driver {} /install",
                    di.inf_path
                )?;
            }
        }

        writeln!(playbook)?;
        Ok(())
    }

    /// Export plan as JSON
    pub fn to_json(plan: &FixPlan) -> Result<String> {
        Ok(serde_json::to_string_pretty(plan)?)
    }

    /// Export plan as YAML
    pub fn to_yaml(plan: &FixPlan) -> Result<String> {
        Ok(serde_yaml::to_string(plan)?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    fn create_test_plan_with_operations() -> FixPlan {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        // FileEdit operation
        plan.add_operation(Operation {
            id: "op-001".to_string(),
            op_type: OperationType::FileEdit(FileEdit {
                file: "/etc/ssh/sshd_config".to_string(),
                backup: true,
                changes: vec![FileChange {
                    line: 15,
                    before: "PermitRootLogin yes".to_string(),
                    after: "PermitRootLogin no".to_string(),
                    context: None,
                }],
            }),
            priority: Priority::High,
            description: "Disable root login".to_string(),
            risk: Priority::Medium,
            reversible: true,
            depends_on: vec![],
            validation: Some(ValidationCheck {
                command: "grep 'PermitRootLogin no' /etc/ssh/sshd_config".to_string(),
                expected_exit: 0,
                expected_output: None,
            }),
            undo: None,
        });

        // PackageInstall operation
        plan.add_operation(Operation {
            id: "op-002".to_string(),
            op_type: OperationType::PackageInstall(PackageInstall {
                packages: vec!["fail2ban".to_string(), "aide".to_string()],
                estimated_size: Some("25MB".to_string()),
                host_cache: None,
            }),
            priority: Priority::Medium,
            description: "Install security packages".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        // ServiceOperation
        plan.add_operation(Operation {
            id: "op-003".to_string(),
            op_type: OperationType::ServiceOperation(ServiceOperation {
                service: "firewalld".to_string(),
                state: Some("enabled".to_string()),
                start: true,
                restart: false,
            }),
            priority: Priority::High,
            description: "Enable firewall".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        plan
    }

    #[test]
    fn test_bash_export() {
        let plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());
        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("GuestKit"));
    }

    #[test]
    fn test_json_export() {
        let plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());
        let json = PlanExporter::to_json(&plan).unwrap();
        assert!(json.contains("security"));
    }

    #[test]
    fn test_bash_export_with_operations() {
        let plan = create_test_plan_with_operations();
        let script = PlanExporter::to_bash(&plan).unwrap();

        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("set -e"));
        assert!(script.contains("BACKUP_DIR"));
        assert!(script.contains("sshd_config"));
        assert!(script.contains("fail2ban"));
        assert!(script.contains("firewalld"));
    }

    #[test]
    fn test_bash_export_file_edit() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-sed".to_string(),
            op_type: OperationType::FileEdit(FileEdit {
                file: "/etc/config".to_string(),
                backup: true,
                changes: vec![FileChange {
                    line: 1,
                    before: "old".to_string(),
                    after: "new".to_string(),
                    context: None,
                }],
            }),
            priority: Priority::Medium,
            description: "Edit config".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("sed -i"));
        assert!(script.contains("/etc/config"));
    }

    #[test]
    fn test_bash_export_package_install() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-pkg".to_string(),
            op_type: OperationType::PackageInstall(PackageInstall {
                packages: vec!["pkg1".to_string(), "pkg2".to_string()],
                estimated_size: None,
                host_cache: None,
            }),
            priority: Priority::Medium,
            description: "Install packages".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("dnf install -y"));
        assert!(script.contains("pkg1"));
        assert!(script.contains("pkg2"));
    }

    #[test]
    fn test_bash_export_service_operation() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-svc".to_string(),
            op_type: OperationType::ServiceOperation(ServiceOperation {
                service: "nginx".to_string(),
                state: Some("enabled".to_string()),
                start: false,
                restart: true,
            }),
            priority: Priority::Medium,
            description: "Restart nginx".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("systemctl enable 'nginx'"));
        assert!(script.contains("systemctl restart 'nginx'"));
    }

    #[test]
    fn test_bash_export_selinux_mode() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-sel".to_string(),
            op_type: OperationType::SelinuxMode(SELinuxMode {
                file: "/etc/selinux/config".to_string(),
                current: "permissive".to_string(),
                target: "enforcing".to_string(),
                warning: None,
            }),
            priority: Priority::High,
            description: "Set SELinux".to_string(),
            risk: Priority::Medium,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("SELINUX="));
        assert!(script.contains("permissive"));
        assert!(script.contains("enforcing"));
    }

    #[test]
    fn test_bash_export_command_exec() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-cmd".to_string(),
            op_type: OperationType::CommandExec(CommandExec {
                command: "echo 'test command'".to_string(),
                expected_exit: 0,
                timeout: None,
                interpreter: None,
            }),
            priority: Priority::Low,
            description: "Run command".to_string(),
            risk: Priority::Low,
            reversible: false,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("echo 'test command'"));
    }

    #[test]
    fn test_bash_export_file_copy() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-cp".to_string(),
            op_type: OperationType::FileCopy(FileCopy {
                source: "/etc/default".to_string(),
                destination: "/etc/config".to_string(),
                backup: true,
            }),
            priority: Priority::Medium,
            description: "Copy file".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("cp"));
        assert!(script.contains("/etc/default"));
        assert!(script.contains("/etc/config"));
    }

    #[test]
    fn test_bash_export_directory_create() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-dir".to_string(),
            op_type: OperationType::DirectoryCreate(DirectoryCreate {
                path: "/var/log/audit".to_string(),
                mode: Some("0755".to_string()),
            }),
            priority: Priority::Low,
            description: "Create directory".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("mkdir -p"));
        assert!(script.contains("0755"));
        assert!(script.contains("/var/log/audit"));
    }

    #[test]
    fn test_bash_export_file_permissions() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-perm".to_string(),
            op_type: OperationType::FilePermissions(FilePermissions {
                path: "/etc/shadow".to_string(),
                mode: "0000".to_string(),
                owner: Some("root".to_string()),
                group: None,
            }),
            priority: Priority::High,
            description: "Set permissions".to_string(),
            risk: Priority::Medium,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("chmod '0000'"));
        assert!(script.contains("chown 'root'"));
        assert!(script.contains("'/etc/shadow'"));
    }

    #[test]
    fn test_bash_export_with_validation() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-val".to_string(),
            op_type: OperationType::CommandExec(CommandExec {
                command: "systemctl start nginx".to_string(),
                expected_exit: 0,
                timeout: None,
                interpreter: None,
            }),
            priority: Priority::Medium,
            description: "Start nginx".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: Some(ValidationCheck {
                command: "systemctl is-active nginx".to_string(),
                expected_exit: 0,
                expected_output: None,
            }),
            undo: None,
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("systemctl is-active nginx"));
        assert!(script.contains("Validation failed"));
    }

    #[test]
    fn test_bash_export_with_post_apply() {
        let mut plan = create_test_plan_with_operations();

        plan.post_apply.push(PostApplyAction::ServiceRestart {
            services: vec!["sshd".to_string(), "nginx".to_string()],
        });

        plan.post_apply.push(PostApplyAction::Message {
            message: "Configuration complete".to_string(),
        });

        let script = PlanExporter::to_bash(&plan).unwrap();
        assert!(script.contains("systemctl restart 'sshd'"));
        assert!(script.contains("systemctl restart 'nginx'"));
        assert!(script.contains("Configuration complete"));
    }

    #[test]
    fn test_ansible_export() {
        let plan = create_test_plan_with_operations();
        let playbook = PlanExporter::to_ansible(&plan).unwrap();

        assert!(playbook.contains("---"));
        assert!(playbook.contains("hosts: vm"));
        assert!(playbook.contains("become: yes"));
        assert!(playbook.contains("tasks:"));
    }

    #[test]
    fn test_ansible_export_file_edit() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-001".to_string(),
            op_type: OperationType::FileEdit(FileEdit {
                file: "/etc/config".to_string(),
                backup: true,
                changes: vec![FileChange {
                    line: 1,
                    before: "old_value".to_string(),
                    after: "new_value".to_string(),
                    context: None,
                }],
            }),
            priority: Priority::Medium,
            description: "Update config".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let playbook = PlanExporter::to_ansible(&plan).unwrap();
        assert!(playbook.contains("lineinfile:"));
        assert!(playbook.contains("path: /etc/config"));
        assert!(playbook.contains("backup: yes"));
    }

    #[test]
    fn test_ansible_export_package_install() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-pkg".to_string(),
            op_type: OperationType::PackageInstall(PackageInstall {
                packages: vec!["vim".to_string(), "git".to_string()],
                estimated_size: None,
                host_cache: None,
            }),
            priority: Priority::Low,
            description: "Install tools".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let playbook = PlanExporter::to_ansible(&plan).unwrap();
        assert!(playbook.contains("package:"));
        assert!(playbook.contains("- vim"));
        assert!(playbook.contains("- git"));
        assert!(playbook.contains("state: present"));
    }

    #[test]
    fn test_ansible_export_service_operation() {
        let mut plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());

        plan.add_operation(Operation {
            id: "op-svc".to_string(),
            op_type: OperationType::ServiceOperation(ServiceOperation {
                service: "httpd".to_string(),
                state: Some("enabled".to_string()),
                start: true,
                restart: false,
            }),
            priority: Priority::Medium,
            description: "Enable httpd".to_string(),
            risk: Priority::Low,
            reversible: true,
            depends_on: vec![],
            validation: None,
            undo: None,
        });

        let playbook = PlanExporter::to_ansible(&plan).unwrap();
        assert!(playbook.contains("service:"));
        assert!(playbook.contains("name: httpd"));
        assert!(playbook.contains("enabled: true"));
        assert!(playbook.contains("state: started"));
    }

    #[test]
    fn test_yaml_export() {
        let plan = FixPlan::new("test.qcow2".to_string(), "security".to_string());
        let yaml = PlanExporter::to_yaml(&plan).unwrap();

        assert!(yaml.contains("vm:"));
        assert!(yaml.contains("test.qcow2"));
        assert!(yaml.contains("profile:"));
        assert!(yaml.contains("security"));
    }

    #[test]
    fn test_json_export_structure() {
        let plan = create_test_plan_with_operations();
        let json = PlanExporter::to_json(&plan).unwrap();

        assert!(json.contains("\"vm\""));
        assert!(json.contains("\"profile\""));
        assert!(json.contains("\"operations\""));
        assert!(json.contains("\"op-001\""));
    }
}
